name: matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: log version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name:  log version again
        run: node -v
