name: Shell

env: 
  blah: "hello!"  

on: 
  push:
    branches: 
      - master

jobs:
  run-shell-command:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: message
        run: echo "Test 1,2,3"
      - name: multiple
        if: always()
        run: |
          node -v
          npm -v
      - name: python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-shell-command_win:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: PS
        run: Get-Location
        continue-on-error: true
      - name: Bash
        run: | 
          pwd
          ls
        shell: bash
