name: test 1

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: message
        run: echo "Test 1,2,3"
      - name: multiple
        run: |
          node -v
          npm -v
      - name: python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-shell-command_win:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: PS
        run: Get-Location
      - name: Bash
        run: pwd
        shell: bash
